version: '2.4'

# todo: globus-init service:
# - globusconnectpersonal -setup
# - globusconnectpersonal -start &

services:
  globus-audit:
    build: .
    image: map-ephys-globus-audit:latest
    entrypoint: /bin/sh
    volumes:
      - .:/src/globus-audit
      - ./dot-globusonline:/home/map/.globusonline
    ports:
      - "8888:8888"
    extra_hosts:
       - "db:192.168.1.10"
    volumes:
